"""Auto-generated Pydantic models from OpenAPI specification.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

The models in this package mirror the attrs models in statuspro_public_api_client/models/
but use Pydantic v2 for validation and serialization.

To regenerate these models, run:
    uv run poe generate-pydantic
"""

from .errors import ErrorResponse, MessageResponse, ValidationErrorResponse
from .orders import (
    AddOrderCommentRequest,
    BulkStatusUpdateRequest,
    BulkStatusUpdateResponse,
    Customer,
    HistoryItem,
    LocaleTranslation,
    MailLog,
    OrderListItem,
    OrderListMeta,
    OrderListResponse,
    OrderResponse,
    ProgressTimelineItem,
    SetDueDateRequest,
    Status,
    UpdateOrderStatusRequest,
)
from .statuses import StatusDefinition, ViableStatus

__all__ = [
    "AddOrderCommentRequest",
    "BulkStatusUpdateRequest",
    "BulkStatusUpdateResponse",
    "Customer",
    "ErrorResponse",
    "HistoryItem",
    "LocaleTranslation",
    "MailLog",
    "MessageResponse",
    "OrderListItem",
    "OrderListMeta",
    "OrderListResponse",
    "OrderResponse",
    "ProgressTimelineItem",
    "SetDueDateRequest",
    "Status",
    "StatusDefinition",
    "UpdateOrderStatusRequest",
    "ValidationErrorResponse",
    "ViableStatus",
]
