"""Auto-generated Pydantic models - errors domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from statuspro_public_api_client.models_pydantic._base import StatusProPydanticBase


class ErrorResponse(StatusProPydanticBase):
    message: str | None = None


class ValidationErrorResponse(StatusProPydanticBase):
    message: str | None = None
    errors: dict[str, list[str]] | None = None


class MessageResponse(StatusProPydanticBase):
    message: str
