"""Auto-generated Pydantic models - orders domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import AwareDatetime, EmailStr, Field

from statuspro_public_api_client.models_pydantic._base import StatusProPydanticBase


class UpdateOrderStatusRequest(StatusProPydanticBase):
    status_code: str
    comment: str | None = None
    public: bool | None = False
    email_customer: bool | None = True
    email_additional: bool | None = True


class BulkStatusUpdateRequest(StatusProPydanticBase):
    order_ids: Annotated[list[int], Field(max_length=50, min_length=1)]
    status_code: str
    comment: str | None = None
    public: bool | None = False
    email_customer: bool | None = True
    email_additional: bool | None = True
    send_at: Annotated[
        int | None, Field(description="Unix timestamp to schedule status emails.")
    ] = None
    due_date: date | None = None


class BulkStatusUpdateResponse(StatusProPydanticBase):
    message: str
    count: int
    limit: int


class AddOrderCommentRequest(StatusProPydanticBase):
    comment: Annotated[str, Field(max_length=1000, min_length=3)]
    public: bool | None = False


class SetDueDateRequest(StatusProPydanticBase):
    due_date: date | None
    due_date_to: date | None = None


class Customer(StatusProPydanticBase):
    name: str | None = None
    email: EmailStr | None = None
    locale: str | None = None


class LocaleTranslation(StatusProPydanticBase):
    name: str | None = None
    description: str | None = None


class Status(StatusProPydanticBase):
    is_set: bool | None = None
    code: str | None = None
    name: str | None = None
    public_name: str | None = None
    description: str | None = None
    public: bool | None = None
    set_at: AwareDatetime | None = None
    auto_change_at: AwareDatetime | None = None
    translations: dict[str, LocaleTranslation] | None = None


class MailLog(StatusProPydanticBase):
    from_: Annotated[EmailStr | None, Field(alias="from")] = None
    to: EmailStr | None = None
    subject: str | None = None
    delivery_status: str | None = None


class HistoryItem(StatusProPydanticBase):
    event: str | None = None
    status: Annotated[Status | None, Field()] = None
    comment: str | None = None
    comment_is_public: bool | None = None
    created_at: AwareDatetime | None = None
    mail_log: Annotated[MailLog | None, Field()] = None


class ProgressTimelineItem(StatusProPydanticBase):
    name: str | None = None
    description: str | None = None
    progress: str | None = None
    timestamp: str | None = None


class OrderResponse(StatusProPydanticBase):
    id: int | None = None
    name: str | None = None
    order_number: str | None = None
    customer: Customer | None = None
    status: Status | None = None
    history: list[HistoryItem] | None = None
    public_progress_timeline: list[ProgressTimelineItem] | None = None
    due_date: AwareDatetime | None = None
    due_date_to: AwareDatetime | None = None


class OrderListItem(StatusProPydanticBase):
    id: int | None = None
    name: str | None = None
    order_number: str | None = None
    customer: Customer | None = None
    status: Status | None = None
    due_date: AwareDatetime | None = None
    due_date_to: AwareDatetime | None = None
    history_count: int | None = None


class OrderListMeta(StatusProPydanticBase):
    current_page: int | None = None
    from_: Annotated[int | None, Field(alias="from")] = None
    last_page: int | None = None
    per_page: int | None = None
    to: int | None = None
    total: int | None = None


class OrderListResponse(StatusProPydanticBase):
    data: list[OrderListItem]
    meta: OrderListMeta
