"""Auto-generated Pydantic models - statuses domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from statuspro_public_api_client.models_pydantic._base import StatusProPydanticBase


class StatusDefinition(StatusProPydanticBase):
    name: str | None = None
    description: str | None = None
    code: str | None = None
    color: str | None = None


class ViableStatus(StatusProPydanticBase):
    code: str | None = None
    name: str | None = None
    description: str | None = None
    color: str | None = None
