"""Auto-generated registry mapping attrs <-> Pydantic model classes.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

# Import all model classes
from statuspro_public_api_client.models.add_order_comment_request import (
    AddOrderCommentRequest as AttrsAddOrderCommentRequest,
)
from statuspro_public_api_client.models.bulk_status_update_request import (
    BulkStatusUpdateRequest as AttrsBulkStatusUpdateRequest,
)
from statuspro_public_api_client.models.bulk_status_update_response import (
    BulkStatusUpdateResponse as AttrsBulkStatusUpdateResponse,
)
from statuspro_public_api_client.models.customer import Customer as AttrsCustomer
from statuspro_public_api_client.models.error_response import (
    ErrorResponse as AttrsErrorResponse,
)
from statuspro_public_api_client.models.history_item import (
    HistoryItem as AttrsHistoryItem,
)
from statuspro_public_api_client.models.locale_translation import (
    LocaleTranslation as AttrsLocaleTranslation,
)
from statuspro_public_api_client.models.mail_log import MailLog as AttrsMailLog
from statuspro_public_api_client.models.message_response import (
    MessageResponse as AttrsMessageResponse,
)
from statuspro_public_api_client.models.order_list_item import (
    OrderListItem as AttrsOrderListItem,
)
from statuspro_public_api_client.models.order_list_meta import (
    OrderListMeta as AttrsOrderListMeta,
)
from statuspro_public_api_client.models.order_list_response import (
    OrderListResponse as AttrsOrderListResponse,
)
from statuspro_public_api_client.models.order_response import (
    OrderResponse as AttrsOrderResponse,
)
from statuspro_public_api_client.models.progress_timeline_item import (
    ProgressTimelineItem as AttrsProgressTimelineItem,
)
from statuspro_public_api_client.models.set_due_date_request import (
    SetDueDateRequest as AttrsSetDueDateRequest,
)
from statuspro_public_api_client.models.status import Status as AttrsStatus
from statuspro_public_api_client.models.status_definition import (
    StatusDefinition as AttrsStatusDefinition,
)
from statuspro_public_api_client.models.update_order_status_request import (
    UpdateOrderStatusRequest as AttrsUpdateOrderStatusRequest,
)
from statuspro_public_api_client.models.validation_error_response import (
    ValidationErrorResponse as AttrsValidationErrorResponse,
)
from statuspro_public_api_client.models.viable_status import (
    ViableStatus as AttrsViableStatus,
)

from ._generated.errors import (
    ErrorResponse as PydanticErrorResponse,
    MessageResponse as PydanticMessageResponse,
    ValidationErrorResponse as PydanticValidationErrorResponse,
)
from ._generated.orders import (
    AddOrderCommentRequest as PydanticAddOrderCommentRequest,
    BulkStatusUpdateRequest as PydanticBulkStatusUpdateRequest,
    BulkStatusUpdateResponse as PydanticBulkStatusUpdateResponse,
    Customer as PydanticCustomer,
    HistoryItem as PydanticHistoryItem,
    LocaleTranslation as PydanticLocaleTranslation,
    MailLog as PydanticMailLog,
    OrderListItem as PydanticOrderListItem,
    OrderListMeta as PydanticOrderListMeta,
    OrderListResponse as PydanticOrderListResponse,
    OrderResponse as PydanticOrderResponse,
    ProgressTimelineItem as PydanticProgressTimelineItem,
    SetDueDateRequest as PydanticSetDueDateRequest,
    Status as PydanticStatus,
    UpdateOrderStatusRequest as PydanticUpdateOrderStatusRequest,
)
from ._generated.statuses import (
    StatusDefinition as PydanticStatusDefinition,
    ViableStatus as PydanticViableStatus,
)
from ._registry import register


def register_all_models() -> None:
    """Register all attrs <-> Pydantic model mappings."""
    register(AttrsAddOrderCommentRequest, PydanticAddOrderCommentRequest)
    register(AttrsBulkStatusUpdateRequest, PydanticBulkStatusUpdateRequest)
    register(AttrsBulkStatusUpdateResponse, PydanticBulkStatusUpdateResponse)
    register(AttrsCustomer, PydanticCustomer)
    register(AttrsErrorResponse, PydanticErrorResponse)
    register(AttrsHistoryItem, PydanticHistoryItem)
    register(AttrsLocaleTranslation, PydanticLocaleTranslation)
    register(AttrsMailLog, PydanticMailLog)
    register(AttrsMessageResponse, PydanticMessageResponse)
    register(AttrsOrderListItem, PydanticOrderListItem)
    register(AttrsOrderListMeta, PydanticOrderListMeta)
    register(AttrsOrderListResponse, PydanticOrderListResponse)
    register(AttrsOrderResponse, PydanticOrderResponse)
    register(AttrsProgressTimelineItem, PydanticProgressTimelineItem)
    register(AttrsSetDueDateRequest, PydanticSetDueDateRequest)
    register(AttrsStatus, PydanticStatus)
    register(AttrsStatusDefinition, PydanticStatusDefinition)
    register(AttrsUpdateOrderStatusRequest, PydanticUpdateOrderStatusRequest)
    register(AttrsValidationErrorResponse, PydanticValidationErrorResponse)
    register(AttrsViableStatus, PydanticViableStatus)
